name: Docker Image CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: hqcbaregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build the Docker image
        run: sudo ./gradlew :fineract-provider:jibDockerBuild -x test

      - name: Tag the Docker image
        run: docker tag rsm-dashboard hqcbaregistry.azurecr.io/fineract:v0.0.1

      - name: Push the Docker image to ACR
        run: docker push hqcbaregistry.azurecr.io/fineract:v0.0.1
